### ISSUE TITLE
Crashes on Java 8

### ISSUE THREAD

**Issue by comp500** [Raxdiam/TeamPerms#5]
`teamperms.mixins.json` has it's compatibilityLevel set to JAVA_14, so Java 8 doesn't work with this mod. I'd suggest supporting Java 8 as most servers will be set up to use it, and some server management panels won't let you choose a different version of Java.

**Comment by Raxdiam** [comment]
This should no longer be an issue as of commit cde7e6c540e4c45f6fc9cf7b8b18436ce76ebea3
